#!/bin/sh
# -*- mode:sh; sh-indentation:2; intent-tabs-mode:nil; -*-
# ex: filetype=sh tabstop=2 softtabstop=2 shiftwidth=2 expandtab autoindent smartindent
set -e

# Compile python resources
# NOTE: we implement our own 'python-support' in order to package Python 2.7
#       even on platforms where it is deprecated   
if which pycompile >/dev/null 2>&1; then
  pycompile -p simple-imager-monitor-python2.7
fi

exit 0

