#!/bin/bash
### BEGIN INIT INFO
# Provides:       si_server
# Required-Start: $remote_fs
# Required-Stop:  $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Simple Imager server services
### END INIT INFO

SI_SERVER=/usr/sbin/si_server

. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting Simple Imager server services..."
    ${SI_SERVER} start >/dev/null
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping Simple Imager server services..."
    ${SI_SERVER} stop >/dev/null
    log_end_msg $?
    ;;
  restart)
    log_begin_msg "Restarting Simple Imager server services..."
    ${SI_SERVER} restart >/dev/null
    log_end_msg $?
    ;;
  status)
    ${SI_SERVER} status
    exit $?
    ;;
  force-reload|condrestart|reload)
    exit 3
    ;;
    *)
    exit 2
    ;;
esac

exit 0

