#!/bin/sh
set -e

case "$1" in
  'configure')
     if ! getent passwd si_server >/dev/null; then
       # Create ad-hoc system user/group
       adduser --system --group \
               --home /var/run/si_server/ \
               --gecos 'Simple Imager Server daemon(s)' \
               --no-create-home \
               si_server
     fi
     ;;
esac

#DEBHELPER#

